/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_H
#define	_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define RUBY_STABILITY "___dtrace_stability$ruby$v1$5_5_5_1_1_0_1_1_0_5_5_0_5_5_0"

#define RUBY_TYPEDEFS "___dtrace_typedefs$ruby$v2"

#define	RUBY_LINE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " RUBY_TYPEDEFS); \
	__dtrace_probe$ruby$line$v1$63686172202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " RUBY_STABILITY); \
} while (0)
#define	RUBY_LINE_ENABLED() \
	__dtrace_isenabled$ruby$line$v1()


extern void __dtrace_probe$ruby$line$v1$63686172202a$696e74(char *, int);
extern int __dtrace_isenabled$ruby$line$v1(void);

#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H */
